"""'pinned_not_null'

Revision ID: 062add848966
Revises: 3d90b7572170
Create Date: 2024-09-10 19:04:46.064322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062add848966'
down_revision: Union[str, None] = '3d90b7572170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
