"""ratelimit_by_ip_2

Revision ID: 20c2b44862c4
Revises: 50b8cef74cb0
Create Date: 2024-12-28 15:01:54.987373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20c2b44862c4'
down_revision: Union[str, None] = '50b8cef74cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratelimit_log', sa.Column('uuid', sa.Uuid(), nullable=False))
    op.alter_column('ratelimit_log', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ratelimit_log', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('ratelimit_log', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratelimit_log', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('ratelimit_log', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ratelimit_log', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('ratelimit_log', 'uuid')
    # ### end Alembic commands ###
