"""'initial'

Revision ID: 3b11bad2b3f4
Revises: 
Create Date: 2024-09-06 23:54:00.151303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b11bad2b3f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('context_size', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('message',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('chat_uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('context_size', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['chat_uuid'], ['chat.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('reply',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('from_uuid', sa.Uuid(), nullable=False),
    sa.Column('to_uuid', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_uuid'], ['message.uuid'], ),
    sa.ForeignKeyConstraint(['to_uuid'], ['message.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('message')
    op.drop_table('chat')
    # ### end Alembic commands ###
