"""'pinned_chats'

Revision ID: 3d90b7572170
Revises: bbe3fdd76cbb
Create Date: 2024-09-10 19:03:00.082021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d90b7572170'
down_revision: Union[str, None] = 'bbe3fdd76cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'pinned')
    # ### end Alembic commands ###
