"""'add_user_to_message'

Revision ID: bbe3fdd76cbb
Revises: d2a8f8732d00
Create Date: 2024-09-09 22:51:06.522487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe3fdd76cbb'
down_revision: Union[str, None] = 'd2a8f8732d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'user')
    # ### end Alembic commands ###
