"""'updated_at_chats'

Revision ID: 52219b641d92
Revises: e3d872d39a42
Create Date: 2024-09-10 19:11:13.833392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52219b641d92'
down_revision: Union[str, None] = 'e3d872d39a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'updated_at')
    # ### end Alembic commands ###
