"""'reply'

Revision ID: cec27e6dcacd
Revises: 3b11bad2b3f4
Create Date: 2024-09-07 08:45:51.764866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec27e6dcacd'
down_revision: Union[str, None] = '3b11bad2b3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'context_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('context_size', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
