"""ratelimit_by_ip

Revision ID: 50b8cef74cb0
Revises: 9d7ee1fcb0fe
Create Date: 2024-12-28 14:59:05.868619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b8cef74cb0'
down_revision: Union[str, None] = '9d7ee1fcb0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratelimit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratelimit_log_ip_address'), 'ratelimit_log', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratelimit_log_ip_address'), table_name='ratelimit_log')
    op.drop_table('ratelimit_log')
    # ### end Alembic commands ###
