"""'add_chat_color'

Revision ID: 9d7ee1fcb0fe
Revises: 52219b641d92
Create Date: 2024-09-20 16:39:50.690522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7ee1fcb0fe'
down_revision: Union[str, None] = '52219b641d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('color', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'color')
    # ### end Alembic commands ###
